language: java
jdk:
  - oraclejdk8
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- mvn org.jetbrains.kotlin:kotlin-maven-plugin:1.2.30:compile
- mvn install
script:
- "./aws-upload.sh"